services:
  web:
    build: .
    ports:
      - "3001:80"
    deploy:
      resources:
        limits:
          cpus: '1'
#    volumes:
#     - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge