services:
  portal-app:
    container_name: portal-app
    build: .
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=portal.htmed.com.br
      - LETSENCRYPT_HOST=portal.htmed.com.br
    networks:
      - proxy-tier
      - default # Mantenha esta rede se você tiver outros containers internos
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '800M'

networks:
  proxy-tier:
    external: true
