services:
  web:
    build: .
    ports:
      - "3008:80"
    volumes:
      - .:/var/www/html
    environment:
      - APPLICATION_ENV=docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge