<div class="panel panel-primary">
    <div class="panel-heading"><i class="fa fa-bar-chart"></i>Relatórios Operacionais</div>
    <div class="panel-body">
        <a class="btn btn-primary" href="/relatorio/agendamento" target=""><i class="fa fa-chevron-right"></i>Relatório Agendados</a>
        <a class="btn btn-primary" href="/relatorio/funcionario" target=""><i class="fa fa-chevron-right"></i>Relatório Funcionário</a>
        <a class="btn btn-primary" href="/relatorio/graficos" target=""><i class="fa fa-chevron-right"></i>Relatório Graficos</a>
        <!--<a class="btn btn-primary" href="/relatorio/convocacao-periodico" target=""><i class="fa fa-chevron-right"></i>Relatório de Convocação de Periódicos</a>-->
        <a class="btn btn-primary" href="/relatorio/biometria" target=""><i class="fa fa-chevron-right"></i>Relatório Biometria</a>
        <!-- <a class="btn btn-primary" href="/relatorio/analitico-pcmso" target="_blank"><i class="fa fa-chevron-right"></i>Relatório Analítico do Pcmso</a> -->
        <a class="btn btn-primary" href="/relatorio/analitico-pcmso" target="_blank"><i class="fa fa-chevron-right"></i>Relatório Analítico do Pcmso</a>
    </div>
</div>