<div class="panel panel-primary">

    <div class="panel-heading"><i class="fa fa-users"></i>Informações do Funcionário</div>

    <div class="panel-body">

        <div class="row">

            <div class="col-md-2">
                <div class="form-group">
                    <label>Cod. Localizador</label>
                    <input type="text" value="<?php echo $this->form['funcionario_localizador_arquivo'] ?>" class="form-control" disabled="true"/>
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <label>CPF</label>
                    <input type="text" value="<?php echo $this->form['pessoa_cpf'] ?>" class="form-control mask-cpf" disabled="true"/>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    <label>Nome</label>
                    <input type="text" value="<?php echo $this->form['pessoa_nome'] ?>" class="form-control" disabled="true"/>
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <label>Identidade</label>
                    <input type="text" value="<?php echo $this->form['pessoa_identidade'] ?>" class="form-control" disabled="true"/>
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <label>Data Nascimento</label>
                    <input type="text" value="<?php echo Util::dataBR($this->form['pessoa_data_nascimento']) ?>" class="form-control" disabled="true"/>
                </div>
            </div>

            <div class="col-md-1">
                <div class="form-group">
                    <label>Sexo</label>
                    <input type="text" value="<?php echo $this->form['pessoa_sexo'] ?>" class="form-control" disabled="true"/>
                </div>
            </div>

        </div>

        <div class="row">

            <div class="col-md-2">
                <div class="form-group">
                    <label>Contrato</label>
                    <input type="text" class="form-control" disabled="disabled" value="<?php echo $this->form['contrato_numero'] ?>">
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <label>Razão Social</label>
                    <input type="text" class="form-control" disabled="disabled" value="<?php echo $this->form['empresa_razao'] ?>">
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <label>Nome Fantasia / Obra</label>
                    <input type="text" class="form-control" disabled="disabled" value="<?php echo $this->form['empresa_fantasia'] ?>">
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <label>Mudar Empresa</label>
                    <button <?php echo (count($this->colecaoProntuarioPorEmpresa) <= 1) ? 'disabled="true"' : null ?> id="mudar-contexto-info-empresa" class="btn btn-info btn-block" style="text-transform: none!important"><span class="icon icon-search icon-white"></span>&nbsp;Selecionar</button>
                </div>
            </div>

        </div>

    </div>

</div>

<div class="row">

    <div class="col-md-6">

        <div class="panel panel-primary alinhar-altura">

            <div class="panel-heading"><i class="fa fa-medkit"></i>Histórico de Exames</div>

            <div class="panel-body">
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th class="fit"><i class="fa fa-bolt no-margin"></i></th>
                            <th>Data</th>
                            <th>Tipo Exame / Procedimento</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->colecaoGridExames as $item): ?>
                            <tr>
                                <td class="fit">
                                    <a class="btn btn-xs btn-default" href="/acervo-digital/adicionar/frm/dossie-medico/protuario_id/<?php echo $item['prontuario_id'] ?>"><span class="fa fa-folder no-margin"></span></a>
                                </td>
                                <td><?php echo Util::dataBR($item['prontuario_data']) ?></td>
                                <td><?php echo mb_strtoupper($item['prontuario_descricao']) ?></td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>

        </div>

    </div>

    <div class="col-md-6">

        <div class="panel panel-primary alinhar-altura">

            <div class="panel-heading"><i class="fa fa-flag"></i>Histórico de Treinamentos</div>

            <div class="panel-body">
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th class="fit"><i class="fa fa-bolt no-margin"></i></th>
                            <th>Data</th>
                            <th>Treinamento</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->colecaoGridTreinamentos as $item): ?>
                            <tr>
                                <td class="fit"><a class="btn btn-xs btn-default" href="/acervo-digital/adicionar/frm/dossie-treinamento/protuario_id/<?php echo $item['prontuario_id'] ?>"><span class="fa fa-folder no-margin"></span></a></td>
                                <td><?php echo Util::dataBR($item['prontuario_data']) ?></td>
                                <td><?php echo $item['prontuario_descricao'] ?></td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

<div id="modal-info-empresas" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="z-index: 1000">×</button>
                <h3 id="modal-info-empresas-label">Informações da Empresa</h3>
            </div>
            <div class="modal-body">
                <p>Selecione um registro para mudar contexto da empresa e contrato</p>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="icones-td">#</th>
                            <th>Contrato</th>
                            <th>Razão Social</th>
                            <th>Nome Fantasia / Obra</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->colecaoProntuarioPorEmpresa as $item): ?>
                            <tr>
                                <td><a href="/acervo-digital/index/funcionario_id/<?php echo $this->form['funcionario_id'] ?>/empresa_id/<?php echo $item['empresa_id'] ?>/contrato_id/<?php echo $item['contrato_id'] ?>"><span class="icon icon-ok"></span></a></td>
                                <td><a href="/acervo-digital/index/funcionario_id/<?php echo $this->form['funcionario_id'] ?>/empresa_id/<?php echo $item['empresa_id'] ?>/contrato_id/<?php echo $item['contrato_id'] ?>"><?php echo $item['contrato_numero'] ?></a></td>
                                <td><a href="/acervo-digital/index/funcionario_id/<?php echo $this->form['funcionario_id'] ?>/empresa_id/<?php echo $item['empresa_id'] ?>/contrato_id/<?php echo $item['contrato_id'] ?>"><?php echo $item['empresa_razao'] ?></a></td>
                                <td><a href="/acervo-digital/index/funcionario_id/<?php echo $this->form['funcionario_id'] ?>/empresa_id/<?php echo $item['empresa_id'] ?>/contrato_id/<?php echo $item['contrato_id'] ?>"><?php echo $item['empresa_fantasia'] ?></a></td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true" style="text-transform: none!important">Fechar</button>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(function () {
        igualarAlturaPelaClasse('alinhar-altura');
        $("#mudar-contexto-info-empresa").click(function () {
            if (this.disabled == false) {
                $("#modal-info-empresas").modal('show');
            }
        });
    });
</script>