<style type="text/css">
    .campo-customizado { 
        box-shadow: none !important; 
        background: transparent !important; 
        border: none !important; 
        border-radius: 0px !important; 
        margin: 0px !important; 
        padding: 0px !important; 
        width: 100%; 
        float: left;
        font-size: 11px !important
    }
</style>
<script type="text/javascript">
    $(function () {
        $("input").prop('disabled', true);
    });
</script>
<div class="row-fluid">

    <div class="span6">
        <div class="well well-small">
            <fieldset>
                <legend><i class="icon-user"></i>&nbsp;Informações do Funcionário</legend> 
                <div class="row-fluid">

                    <div class="span4">
                        <label>CPF</label>
                        <input type="text" value="<?php echo $this->form['pessoa_cpf'] ?>" class="span mask-cpf" disabled="true"/>
                    </div>

                    <div class="span8">
                        <label>Nome</label>
                        <input type="text" value="<?php echo $this->form['pessoa_nome'] ?>" class="span" disabled="true"/>
                    </div>

                </div>

                <div class="row-fluid">
                    <div class="span4">
                        <label>Identidade</label>
                        <input type="text" value="<?php echo $this->form['pessoa_identidade'] ?>" class="span" disabled="true"/>
                    </div>

                    <div class="span4">
                        <label>Data Nascimento</label>
                        <input type="text" value="<?php echo Util::dataBR($this->form['pessoa_data_nascimento']) ?>" class="span" disabled="true"/>
                    </div>

                    <div class="span4">
                        <label>Sexo</label>
                        <input type="text" value="<?php echo $this->form['pessoa_sexo'] ?>" class="span" disabled="true"/>
                    </div>
                </div>
            </fieldset>

        </div>
    </div>

    <div class="span6">
        <div class="well well-small">
            <fieldset>
                <legend><i class="icon-check"></i>&nbsp;Procedimento Realizados</legend> 
            </fieldset>

            <?php if ($this->exibirQualFormulario == 'dossie-medico'): ?>                

                <div class="row-fluid">
                    <div class="span12">
                        <label>Código Localizador</label>
                        <input type="text" class="span" value="<?php echo $this->form['prontuario_localizador'] ?>" name="prontuario_localizador" required="true"/>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span4">
                        <label>Data</label>
                        <input type="text" class="span mask-data" value="<?php echo Util::dataBR($this->form['prontuario_data']) ?>" name="prontuario_data" required="true"/>
                    </div>
                    <div class="span8">
                        <label>Tipo de Exame</label>
                        <input type="text" class="span" name="prontuario_descricao" value="<?php echo $this->form['prontuario_descricao'] ?>" required="true"/>
                    </div>
                </div>

                <table class="table" style="margin-top: 10px;">
                    <thead>
                        <tr>
                            <th style="width: 10%;text-align: center!important">Data</th>
                            <th style="width: 50%">Procedimento / Documento</th>
                            <th style="width: 10%;text-align: center!important">Validade</th>
                            <th style="width: 10%;text-align: center!important">Exame</th>
                            <th style="width: 10%;text-align: center!important">Laudo</th>
                            <th style="width: 10%;text-align: center!important">Médico</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->colecaoProcedimento as $k => $item): ?>

                            <tr>
                                <td style="text-align: center!important">
                                    <input style="text-align: center!important" readonly="true" class="campo-customizado" type="text" value="<?php echo Util::dataBR($item['procedimento_data']) ?>"/>
                                </td>
                                <td>
                                    <input readonly="true" class="campo-customizado" name="procedimento_nome[<?php echo $k ?>]" type="text" value="<?php echo $item['procedimento_nome'] ?>"/>
                                </td>
                                <td>
                                    <input required="true" style="text-align: center!important" class="campo-customizado mask-data" name="procedimento_data_validade[<?php echo $k ?>]" type="text" value="<?php echo Util::dataBR($item['procedimento_data_validade']) ?>"/>
                                </td>

                                <!-- UPLOAD EXAME -->
                                <td style="text-align: center!important">
                                    <?php if ((int) $item['exame_arquivo_upload_id'] > 0): ?>
                                        <a rel="tooltip" title="Exame" class="ativar-caixa-upload btn btn-info btn-mini" href="/arquivo-upload/descarregar/id/<?php echo $item['exame_arquivo_upload_id'] ?>"><span class="icon-download"></span></a>                                        
                                    <?php endif ?>
                                </td>

                                <!-- UPLOAD LAUDO -->
                                <td style="text-align: center!important">
                                    <?php if ((int) $item['laudo_arquivo_upload_id'] > 0): ?>
                                        <a rel="tooltip" title="Laudo" class="ativar-caixa-upload btn btn-info btn-mini" href="/arquivo-upload/descarregar/id/<?php echo $item['laudo_arquivo_upload_id'] ?>"><span class="icon-download"></span></a>                                        
                                    <?php endif ?>
                                </td>
                                <td style="width: 10%;text-align: center!important">
                                    <input class="item-marcador-checkbox"  type="checkbox" value="1" <?php echo ((int) $item['procedimento_visib_externa_medico'] >= 1) ? 'checked="true"' : null ?> />
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>

                <div class="row-fluid">
                    <div class="span12">
                        <button class="btn btn-default" type="button" onclick="window.location.href = '/acervo-digital/index/cpf/<?php echo $this->form['pessoa_cpf'] ?>'">Voltar</button>
                    </div>                        
                </div>

            <?php endif ?>

            <?php if ($this->exibirQualFormulario == 'dossie-treinamento'): ?>                

                <div class="row-fluid">
                    <div class="span12">
                        <label>Código Localizador</label>
                        <input type="text" class="span" value="<?php echo $this->form['prontuario_localizador'] ?>" name="prontuario_localizador" required="true"/>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span4">
                        <label>Data</label>
                        <input type="text" class="span mask-data" value="<?php echo Util::dataBR($this->form['prontuario_data']) ?>" name="prontuario_data" required="true"/>
                    </div>
                    <div class="span8">
                        <label>Tipo de Exame</label>
                        <input type="text" class="span" name="prontuario_descricao" value="<?php echo $this->form['prontuario_descricao'] ?>" required="true"/>
                    </div>
                </div>

                <table class="table" style="margin-top: 10px;">
                    <thead>
                        <tr>
                            <th style="width: 10%;text-align: center!important">Data</th>
                            <th style="width: 50%">Documento</th>
                            <th style="width: 10%;text-align: center!important">Validade</th>
                            <th style="width: 10%;text-align: center!important">Anexo</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->colecaoProcedimento as $k => $item): ?>

                            <tr>
                                <td style="text-align: center!important">
                                    <input style="text-align: center!important" readonly="true" class="campo-customizado" type="text" value="<?php echo Util::dataBR($item['procedimento_data']) ?>"/>
                                </td>
                                <td>
                                    <input readonly="true" class="campo-customizado" name="procedimento_nome[<?php echo $k ?>]" type="text" value="<?php echo $item['procedimento_nome'] ?>"/>
                                </td>
                                <td>
                                    <input required="true" style="text-align: center!important" class="campo-customizado mask-data" name="procedimento_data_validade[<?php echo $k ?>]" type="text" value="<?php echo Util::dataBR($item['procedimento_data_validade']) ?>"/>
                                </td>
                                <!-- UPLOAD -->
                                <td style="text-align: center!important">
                                    <?php if ((int) $item['arquivo_upload_id'] > 0): ?>
                                        <a rel="tooltip" title="Download" class="ativar-caixa-upload btn btn-info btn-mini" href="/arquivo-upload/descarregar/id/<?php echo $item['arquivo_upload_id'] ?>"><span class="icon-download"></span></a>                                        
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>

                <div class="row-fluid">
                    <div class="span12">
                        <button class="btn btn-default" type="button" onclick="window.location.href = '/acervo-digital/index/cpf/<?php echo $this->form['pessoa_cpf'] ?>'">Voltar</button>
                    </div>                        
                </div>

            <?php endif ?>

        </div>
    </div>



</div>