<?php
$CmsConteudo = new Application_Model_CmsConteudo();
$CmsConteudo->update(array('cms_conteudo_status' => 2),
                     array('cms_conteudo_valido_ate < ?' => date('Y/m/d')));
$banners = $CmsConteudo->obterRelacaoBanners();
#util::dump($banners); 
foreach ($banners as $key => $value) {

    $limite = 25;
    $url = $value['src'];

    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $url);        // Inicia uma nova sessão do cURL
    curl_setopt($curl, CURLOPT_TIMEOUT, $limite); // Define um tempo limite da requisição
    curl_setopt($curl, CURLOPT_NOBODY, true);     // Define que iremos realizar uma requisição "HEAD"
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, false); // Não exibir a saída no navegador
    curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false); // Não verificar o certificado do site

    curl_exec($curl);  // Executa a sessão do cURL
    $status = curl_getinfo($curl, CURLINFO_HTTP_CODE) == 200; // Se a resposta for OK, a URL está ativa
    curl_close($curl); // Fecha a sessão do cURL
    #if ($key == 0) {
        if ($status) {
            #echo "O link fornecido está disponível! ". $value['src'];exit();
            $CmsConteudo->update(array('cms_conteudo_status_url' => 0),
                                 array('cms_conteudo_id = ?' => $value['id']));
        } else {
            #echo "O link fornecido está quebrado. ". $value['src'];exit();
            $CmsConteudo->update(array('cms_conteudo_status_url' => 1),
                                 array('cms_conteudo_id = ?' => $value['id']));
            unset($banners[$key]);
        }
    #}

}
sort($banners);

if (empty($banners)) {
    $banners = array(
        array('src' => "/img/banner03.png", 'txt' => ""),
        array('src' => "/img/banner02.png", 'txt' => ""),
        array('src' => "/img/banner04.png", 'txt' => ""),
        array('src' => "/img/banner01.png", 'txt' => ""),
    );
}
#util::dump($banners); 
?>

<style>

.swal2-title {
  background-color: #2979FF; /* Azul claro, similar à caixa superior da imagem */
  color: #fff;
  text-align: center;
  padding: 1rem;
}

.swal2-content {
  background-color: #00468B; /* Azul escuro, similar à caixa inferior da imagem */
  color: #fff;
  text-align: center;
  padding: 1rem;
}

.swal2-styled {
  font-family: Arial, sans-serif; /* Substitua por uma fonte similar à da imagem */
  font-size: 16px;
}

.swal-container {
  /* Estilos para o container */
  background-color: #fff;
  padding: 20px;
  border-radius: 10px;
}


</style>

<div class="row">

    <div class="col-md-12">

            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">

                    <div class="row">

                        <div class="col-md-4">
                            <div class="panel panel-success card">
                                <div class="panel-heading"><i class="fa fa-success"></i>Funcionários Ativos</div>
                                <div class="panel-body" align="center">
                                    <h3><?php echo $this->funcAtivos ?></h3>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="panel panel-warning card">
                                <div class="panel-heading"><i class="fa fa-warning"></i>Periódicos a vencer (30 dias)</div>
                                <div class="panel-body" align="center">
                                    <h3><?php echo $this->perAvencer ?></h3>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="panel panel-danger card">
                                <div class="panel-heading"><i class="fa fa-warning"></i>Periódicos vencidos</div>
                                <div class="panel-body" align="center">
                                    <h3><?php echo $this->perVencido ?></h3>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
    </div>

</div>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators     
    <ol class="carousel-indicators">
        <?php foreach ($banners as $i => $banner) : ?>        
            <li data-target="#carousel-example-generic" data-slide-to="<?php echo $i ?>" class="<?php echo $i == 0 ? 'active' : '' ?>"></li>
        <?php endforeach; ?>
    </ol>
    -->

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <?php foreach ($banners as $i => $banner) : ?>
            <div class="item <?php echo $i == 0 ? 'active' : '' ?>">
                <img src="<?php echo $banner['src'] ?>" alt="...">
                <br><br><br><br>
                <div class="carousel-caption"><a target="_blank" href="<?php echo @$banner['link'] ?>"><?php echo @$banner['txt'] ?></a></div>
            </div>
        <?php endforeach; ?>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Proximo</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Anterior.</span>
    </a>

</div>

<script>
    $(document).ready(function() {
        
        aviso();
        <?php if (count(@$_SESSION['inadimplecia']) > 0) : ?>
            faturas();
        <?php else : ?>
            <?php if (count($this->qtd) > 0 AND $this->qtd > 0) : ?>
                checkaloc();
            <?php endif ; ?>
        <?php endif ; ?>

    })

    function checkaloc(){
         swal({
              html: true,
              title: "Atenção",
              type: 'warning',              
              text: `Foram identificados `+ <?php echo $this->qtd ?> +` trabalhadores sem o devido número da matrícula e/ou alocação do cargo / função, impedindo o envio das informações ao eSocial. Gentileza proceder a respectiva atualização na aba “Funcionários”.`,                  
              confirmButtonText: "OK", 
              closeOnConfirm: true,
              showLoaderOnConfirm: false
              },
              function(){
                
            });
    }

    function faturas(){
         swal({
              html: true,
              title: "Atenção",
              type: 'warning',              
              //text: `Foram identificados `+ <?php echo count($this->faturastatus) ?> +` pendências financeiras. Gentileza manter contato com nosso departamento financeiro através do telefone (27) 3064-7359 e/ou E-mail: contasareceber.uvc@hiest.com.br.`,
              text: `Gentileza manter contato com nosso departamento financeiro através do telefone (31) 2555-3131 e/ou E-mail: financeiro@htmed.com.br.`,                   
              confirmButtonText: "OK", 
              closeOnConfirm: true,
              showLoaderOnConfirm: false
              },
              function(){
                
            });
    }
    
    function aviso(){
        swal({
            html: true,
            title: "<div style='background-color: #2979FF; color: #fff; padding: 15px; text-align: center; border-radius: 10px;'>Mudamos</div><div style='background-color: #6495ED; color: #fff; padding: 15px; text-align: center; border-radius: 10px;'>de endereço.</div>",
            type: 'warning',
            text: `Estamos atendendo em um novo endereço:<br><br>
                <b>Av. Abílio Machado,<br> 1594 - Loja A</b><br>
                Alipio de Melo - BH<br><br>
                Venha conhecer<br> nosso novo espaço!<br><br>
                <div style='background-color: #6495ED; color: #fff; padding: 15px; text-align: center; border-radius: 10px;'>@htmed_oficial</div><br>
                <div style='background-color: #6495ED; color: #fff; padding: 15px; text-align: center; border-radius: 10px;'>Tel:(31) 2555-3131</div>
                `,
            confirmButtonText: "OK",
            closeOnConfirm: true,
            showLoaderOnConfirm: false
        });
    }
    
</script>

<?php echo $this->render('termos/termo.phtml') ?>

<?php echo $this->render('termos/termoesocialsst.phtml') ?>