
<style type="text/css">
#modal-termos-esocial {
    /*width: 840px !important;
    margin-left: 440px;*/
}
.modal.fade {
    top: 100px;
}
.modal-body {
    height: 50vh;
    overflow-x: auto;
}
</style>

<div class="modal fade" id="modal-termos-esocial" tabindex="-1" role="dialog" data-remote="false" aria-labelledby="modalUnidadesLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Informações do Sistema para ESocial</h3>
            </div>
                <div class="modal-body" role="dialog" >
                    <div class="modal-body" role="dialog" >
                            <div style="width: 100%; text-transform: none;">
                                <p align="center"><b><u>Termo de Ciência ESOCIAL & SST</u></b></p>
                                <br><p align="justify">
                                Sobre o atendimento às demandas da última fase de implantação do <b>eSocial</b>, com envio dos 3 eventos de <b>SST - Segurança e Saúde no Trabalho: S-2210; S-2220 e S-2240</b>.<br><br>

                                É imprescindível a leitura e compreensão dos pontos abaixo a fim de se tomar medidas que evitem multas, autuações e fiscalizações onerosas para a empresa, ocasionadas por irregularidades em documentações, prazos ou declarações, gerando ainda, passivos previdenciário, trabalhista e/ou tributário.<br><br>

                                A HTMED conta, desde já, com a compreensão dos responsáveis legais da sua empresa em <u>dar ciência no presente termo, entendendo e aceitando as informações contidas</u> para andamento no processo e alinhamento das informações.<br><br>

                                O eSocial, Sistema de Escrituração Digital das Obrigações Fiscais, Previdenciárias e Trabalhistas, entrou na 4ª fase de implantação com os eventos de <b>Segurança e Saúde no Trabalho</b>, onde a empresa prestará contas ao Governo declarando informações periódicas sobre o ambiente de trabalho e sobre a monitoração da saúde dos colaboradores. Nas fases anteriores, a contabilidade da sua empresa deve ter enviado todos os dados referentes à mesma (tributos), além das informações dos empregados (folha de pagamento e registro).<br><br>

                                O objetivo é unificar as informações prestadas aos diversos órgãos do Governo Federal e substituir:<br>
                                &nbsp;&nbsp;&nbsp;- a atual forma de emissão da Comunicação de Acidente de Trabalho (CAT)<br>
                                &nbsp;&nbsp;&nbsp;- a atual emissão do Perfil Profissiográfico Previdenciário (PPP)<br><br>

                                Devem ser enviadas informações obtidas durante a realização de exames médicos ocupacionais (Admissional, periódico, dentre outros) e de programas legais já conhecidos e que devem estar vigentes no período, tais como:<br>
                                &nbsp;&nbsp;&nbsp;► <b>PCMSO</b> - Programa de Controle Médico de Saúde Ocupacional<br>
                                &nbsp;&nbsp;&nbsp;► <b>ASO</b> - Atestado de Saúde Ocupacionall<br>
                                &nbsp;&nbsp;&nbsp;► <b>PPRA</b> (previsão de substituição pelo <b>PGR</b> a partir de janeiro / 2022)<br>
                                &nbsp;&nbsp;&nbsp;► <b>LTCAT</b> - Laudo Técnico das Condições Ambientais do Trabalhol<br><br>

                                Mesmo em casos onde a empresa não possua riscos que ensejem aposentadoria especial, o laudo deve ser elaborado para garantir essa ausência e o evento deve ser enviado para cada colaborador com um código específico de ausência de riscos.<br><br>

                                A transmissão ocorre através de eventos, que se dividem da seguinte forma:<br>
                                &nbsp;&nbsp;&nbsp;2240 – Condições Ambiente do Trabalho – agentes nocivos<br>
                                &nbsp;&nbsp;&nbsp;2220 – Monitoração biológica do Trabalhador<br>
                                &nbsp;&nbsp;&nbsp;2210 – Comunicado de Acidente de Trabalho - CAT<br><br>

                                Link para Leiautes dos eventos do eSocial <a href="https://www.gov.br/esocial/pt-br/documentacao-tecnica/leiautes-esocial-html/index.html">aqui.</a><br><br>

                                <b>S-2210 - Comunicação de Acidente do Trabalho</b><br>
                                A Comunicação de Acidente de Trabalho (S-2210) que era realizada pela CAT-WEB passa então a ser enviada como evento para o eSocial e a própria plataforma emitirá a CAT. Deve ser realizada baseando-se nas mesmas regras, com suporte e orientação dos responsáveis técnicos de segurança e do médico do trabalho. Serão usadas as tabelas 13 (parte do corpo atingida); tabela 14 (agente causador do acidente); tabela 15 e tabela 17. <b>O envio das informações não substitui a investigação do acidente e a emissão do atestado médico</b>. O prazo para envio continua de 24h e, em caso de morte, imediatamente.<br><br>

                                <b>S-2220 – Monitoramento da Saúde do Trabalho</b><br>
                                O monitoramento da saúde do trabalhador é realizado através dos exames médicos ocupacionais. São enviadas informações referentes aos exames clínicos e complementares, as quais são originadas do PCMSO, conforme determina a NR-07. Esse evento não demanda carga inicial, registrando as informações que ocorrem a partir do início da obrigatoriedade, ou seja, serão enviados os exames realizados após data de vigência do Grupo a que pertence a empresa e, posteriormente, no dia 15 de cada mês, com dados dos exames do mês anterior.<br><br>

                                <b>S-2240 – Condições Ambientais do Trabalho</b><br>
                                Esse evento tem como objetivo registrar as condições ambientais de trabalho. Para tal, é necessário o desenvolvimento do PPRA (em substituição pelo PGR) e realização de avaliações quantitativas / qualitativas, quando aplicável e respectiva emissão do LTCAT.<br>
                                O prazo de envio é finalizado no dia 15 do mês subsequente a realização, devendo ser transmitida uma carga inicial a partir da data de vigência do Grupo a que pertence a empresa.<br><br>

                                Desenvolvemos em nosso sistema o módulo de Gestão do eSocial, o qual possibilita a transmissão das informações referentes aos atendimentos médicos e respectivos programas legais desenvolvidos conosco. Anteriormente ao envio, os dados são convertidos em um <b>arquivo .xml</b> de acordo com os leiautes disponibilizados pelo eSocial e podem ser transmitidos automaticamente na periodicidade estabelecida. Para tal, a empresa deverá realizar a respectiva autorização, assinando o presente termo e cadastrando uma procuração para a HTMED Seguranca e Medicina do Trabalho (21.969.023/0001-89) no E-CAC (dúvidas, consultar a contabilidade). Importante ressaltar que é necessário que a Coordenação do PCMSO da empresa seja realizada pela HTMED, tendo em visto as exigências legais e responsabilidades médica e técnica envolvidas. Caso essa opção não esteja ativa no contrato, favor nos contatar.<br><br>

                                Caso a empresa já possua sistema preparado para essa finalidade e respectivos profissionais para Gestão das Informações há a possibilidade de disponibilização do arquivo .xml, o que ocorrerá diretamente em nosso portal do cliente.<br><br>
                                
                                Nos colocamos a disposição em caso de eventuais dúvidas e aguardamos o devido retorno para andamento do processo.<br><br></p>
                            </div>
                            <div class="alert alert-warning" >
                                <label class="radio" style="margin-bottom:0 !important; margin-left: 20px;text-transform: none;"><input type="radio" name="usuario_portal_esocial_autoriza" id="usuario_portal_esocial_autoriza" value="1" onclick="Autorizar();" /><b> Declaro estar ciente das informações citadas no presente comunicado, autorizo a transmissão dos dados pela HTMED e me comprometo a cadastrar a respectiva procuração no E-CAC. <b></label>
                                <label class="radio" style="margin-bottom:0 !important; margin-left: 20px;text-transform: none;"><input type="radio" name="usuario_portal_esocial_autoriza" id="usuario_portal_esocial_autoriza" value="2" onclick="Autorizar();" /><b> Declaro estar ciente das informações citadas no presente comunicado e informo que não será necessário o envio das mesmas pela HTMED.<b></label>
                                <label class="radio" style="margin-bottom:0 !important; margin-left: 20px;text-transform: none;"><input type="radio" name="usuario_portal_esocial_autoriza" id="usuario_portal_esocial_autoriza" value="3" onclick="Autorizar();" /><b> Declaro estar ciente das informações citadas no presente comunicado e informo que não será necessário o envio das mesmas pela HTMED. No entanto, tenho interesse no acesso aos dados em arquivo .xml para envio por nossa equipe.<b></label>
                                <label class="radio" style="margin-bottom:0 !important; margin-left: 20px;text-transform: none;"><input type="radio" name="usuario_portal_esocial_autoriza" id="usuario_portal_esocial_autoriza" value="4" onclick="Autorizar();" /><b> Não é possível decidirmos a melhor opção no momento, nos comprometendo a manter contato futuramente para definição.<b></label>
                                <br>
                                <label>Informações do Declarante:</label><br>
                                <label>Nome Completo:</label>
                                <input type="text" name="daclarante_nome" id="daclarante_nome" placeholder="Campo Obrigatório" />
                                <label>CPF:</label>
                                <input class="mask-cpf ignora-ucase" type="text" name="daclarante_cpf" id="daclarante_cpf" placeholder="Campo Obrigatório"/>
                            </div>
                    </div>
                </div>
            <div class="modal-footer">
                <button class="btn btn-success" aria-hidden="true" name="permitir" id="permitir" onclick="autorizar();" disabled><i class="fa fa-check"></i> Confirmar Declaração</button>
            </div>
        </div>
    </div>
</div>

<script>

<?php if (!empty($this->termos['usuario_portal_aceitou_termos']) && empty($this->termos['usuario_portal_esocial_aceitou_termos'])): ?>
    $("#modal-termos-esocial").modal({
        backdrop: 'static',
        keyboard: false
    });
<?php endif?>

function Autorizar() {
    var radios = document.querySelectorAll('input[type="radio"]:checked');
    var value = radios.length > 0 ? radios[0].value: null;

    var nome = $('#daclarante_nome').val();
    var cpf = $('#daclarante_cpf').val();
    
    if (value > 0 && nome != '' && cpf != '') {
        $("#permitir").prop('disabled', false);        
    } else {
        $("#permitir").prop('disabled', true);
    }
}

function autorizar() {
    $("#permitir").html('Aguarde...');
    $("#permitir").prop('disabled', true);

    var radios = document.querySelectorAll('input[type="radio"]:checked');
    var value = radios.length > 0 ? radios[0].value: null;
    var nome = $('#daclarante_nome').val();
    var cpf = $('#daclarante_cpf').val();

    $.post('/ajax/json/servico/aceitar-termos-esocial', {id:value, nome:nome, cpf:cpf}, function (resposta) {
        
        if (resposta == 0) {   
            $("#permitir").prop('disabled', false);
            $("#permitir").html('Aceitar');       
        } else {
            $("#modal-termos-esocial").modal("hide");
            document.getElementById('modal-termos-esocial').classList.add('hide');
            window.location.reload(true);
        }
        
    });
}

</script>
