<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8"/>
        <title>Portal do Cliente &boxdl; Identifique-se</title>
        <link rel="shortcut icon" href="/htmed-favico.png" type="image/png" sizes="16x16"/>
        <link rel="icon" href="/htmed-favico.png" sizes="16x16"/>
        <link rel="stylesheet" href="/bootstrap/css/bootstrap.css" type="text/css" media="all"/>
        <link rel="stylesheet" href="/bootstrap/css/bootstrap-responsive.css" type="text/css" media="all"/>
        <link rel="stylesheet" href="/css/geral.css" type="text/css" media="all"/>
        <script src="/js/jquery-1.10.2.min.js" type="text/javascript"></script>
        <script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
        <script src="/js/geral.js" type="text/javascript"></script>
        <script src="/js/util.js" type="text/javascript"></script>
        <script src="/bootstrap/js/bootstrap.js" type="text/javascript"></script>
        <style type="text/css">
            body { background-color: #fff;margin: 0px;padding: 0px; }
        </style>
    </head>
    <body>

        <div class="container-fluid">

            <div class="row-fluid">

                <div class="span3"></div>

                <div class="span6" >

                    <div class="row-fluid">

                        <div class="well" style="overflow: hidden;margin-top: 15%;">

                            <div class="span7">
                                <h2>PORTAL DO CLIENTE</h2>
                                <p>SISTEMA INTEGRADO DE SAÚDE E SEGURANÇA</p>
                                <p><strong>Bem Vindo!</strong></p>
                                <p style="text-align: justify;">Informe seu login e senha para começar a usar o portal do cliente.</p>
                                <img src="/img/logoHTMED.png" width="200" height="66" />
                            </div>

                            <div class="span5 well" style="background-color: white;">

                                <?php if (count($this->mensagens) > 0): ?>
                                    <div class="alert alert-danger">
                                        <h5>Atenção!</h5>
                                        <?php foreach ($this->mensagens as $mensagem): ?>
                                            <span><?php echo $mensagem ?></span>
                                        <?php endforeach ?>
                                    </div>
                                <?php endif ?>

                                <form method="post" action="/auth/login/">

                                    <legend>Identifique-se!&nbsp;</legend>

                                    <div class="row-fluid">
                                        <div class="span12"><input class="span" placeholder="Nome de usuário" type="text" name="login" value="<?php echo $this->entradas['login'] ?>" /></div>
                                    </div>

                                    <div class="row-fluid">
                                        <div class="span12"><input class="span" placeholder="Senha de acesso" type="password" name="senha" value="" /></div>
                                    </div>

                                    <div class="row-fluid">
                                        <div class="span12"><button class="btn btn-inverse" name="iniciarSessao" type="submit"><i class="icon-ok icon-white"></i>&nbsp;Acessar</button></div>
                                    </div>

                                </form>
                            </div>

                        </div>
                    </div>
                </div>

            </div>

            <div class="span3"></div>

        </div>

        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
            ga('create', 'UA-66852788-1', 'auto');
            ga('send', 'pageview');
        </script>
    </body>
</html>
