<hr style="margin: 0px;">
<div style="font-family: Arial">
    <table  border="0" cellpadding="1" cellspacing="0" width="100%" style="border-radius: 10px;font-family: arial; font-size: 11px;">
        <tr>
            <td width="33%"><img src="/img/logo-relatorio.png" /></td>
            <td style="font-size: 22px Arial" width="34%"><strong><p style="font-size: 22px Arial"><[atributoComercial]/></p></strong></td>
            <td width="24%" style="text-align: center">
                <p style="color: darkblue;">
                    <strong>OS: <[atributoProposta]/></strong>
                </p>
                <p>P. {PAGENO}/{nbpg}</p>
            </td>
        </tr>
    </table>
    <hr style="margin-top: 0px; border: 1px solid;">
    <table  border="0" cellpadding="1" cellspacing="0" width="100%" style="font-family: arial; font-size: 11px;">
        <tr style="border: 0px solid graytext">
            <td style="font-size: 10px">EMPRESA<br><input type="text" style="width: 70%;font-family: Arial" value="<[atributoEmpresa]/>" /></td>
            <td width="25%" style="font-size: 10px">N° DA PROPOSTA<br><input type="text" style="width: 25%;font-family: Arial" value="<[atributoProposta]/>"></td>
        </tr>
    </table>
    <table  border="0" cellpadding="1" cellspacing="0" width="100%" style="font-family: arial; font-size: 11px;">
        <tr style="border: 0px solid graytext">
            <td width="38%" style="font-size: 10px">NOME DO CONTATO<br><input type="text" style="width: 38%; font-size: 10px;font-family: Arial" value="<[atributoNome]/>"></td>
            <td width="35%" style="font-size: 10px">E-MAIL DO CONTATO<br><input type="text" style="width: 31.5%; font-size: 10px;font-family: Arial" value="<[atributoEmail]/>"></td>
            <td width="25%" style="font-size: 10px">TELEFONE DO CONTATO<br><input type="text" style="width: 25%; font-size: 10px;font-family: Arial" value="<[atributoTelefone]/>"></td>
        </tr>
    </table>
    <table  border="0" cellpadding="1" cellspacing="0" width="100%" style="font-family: arial; font-size: 11px;">
        <tr style="border: 0px solid graytext">
            <td width="100%" style="font-size: 10px">LOCAL E DATA<br><input type="text" style="width: 100%; border-radius: 10px; " value="<[atributoLocal]/>"></td>
        </tr>
    </table>
</div>
<hr style="margin-top: 0px; border: 2px solid;">