<?php
require_once 'MPDF/mpdf.php';
$localScripts = '../application/views/scripts/documento-operacional/';
//require_once "{$localScripts}include/funcoes.php";

$htmlRodape = obterHtmlDoRodapeEmPdf();
$htmlCabecalho = file_get_contents($localScripts . 'os/partes/cabecalho.html');

$p = new mPDF('utf-8', 'A4', 0, '', 10, 10, 35, 30, 8, 8);
$p->SetHTMLHeader($htmlCabecalho);
$p->SetHTMLFooter($htmlRodape);
$p->setAutoTopMargin = false;
$p->setAutoBottomMargin = false;
ob_start();
?>
<style>
    table#tabela tr td { font: normal 12px Arial; border: 0px solid #ccc; }
    table{border-collapse: collapse; font: normal 11px Arial;width: 100%;}
    table#tabela tr td.etiqueta { font-weight: bold; padding: 4px; }
    table#tabela tr td.titulo { text-align: center; font-weight: bold; background: #ddd; }
    table#tabela tr td.separador { padding: 10px; border: none; }
    table#tabela tr td.centro { text-align: center; } 
</style>


    
<?php
$htmlCorpo = ob_get_clean();
$htmlCorpo . '</body></html>';
$p->WriteHTML($htmlCorpo);
$p->Output();
