<table  border="0" cellpadding="1" cellspacing="0" style="font-family: arial; font-size: 20px; border: solid 2px white;">
    <tr>
        <td style="width: 100px; border: solid 2px white;"><img src="/img/logoHTMED.png" height="60" width="100"/></td>
        
        <td style="text-align: center; vertical-align: middle;">
            <p style="color: dark;">
                <strong>
                    Recibo de envio eSocial
                </strong>
            </p>    
        </td>
    </tr>
</table> 