<?php ob_start() ?>
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <style type="text/css">
            body {
                font: 10px monospace;
            }
            table {
                border-collapse: collapse;
            }
            table tr td,
            table tr th {
                padding: 4px;
                text-align: center;
                white-space: nowrap;
            }
            table tr.tr-border-bottom td,
            table tr.tr-border-bottom th {
                border-bottom: 1px solid #000 !important;
            }
            table tr.tr-border-top td,
            table tr.tr-border-top th {
                border-top: 1px solid #000;
            }
            table tr.tr-left td,
            table tr.tr-left th {
                text-align: left;
            }
            table tr td.info {
                font-weight: bold;
                text-align: right;
            }
            table tr td.dado {
                text-align: left;
            }
        </style>
    </head>
    <body>
        <table width="100%">
            <tr>
                <td align="left"><img src="/img/logoHTMED.png" width="100"/></td>
                <td><h1>Espelho de Ponto</h1></td>
                <td width="200">1/2</td>
            </tr>
        </table>

        <table width="100%" style="margin: 30px 0;">
            <tr>
                <td class="info" width="1">EMPREGADO:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_nome'] ?></td>
                <td></td>
                <td class="info">PERÍODO:</td>
                <td class="dado"><?php echo Data::converterParaBR($this->ponto['rh_ponto_periodo_1']) . ' a ' . Data::converterParaBR($this->ponto['rh_ponto_periodo_2']) ?></td>
            </tr>
            <tr>
                <td class="info">FUNÇÃO:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_funcao'] ?></td>
                <td></td>
                <td class="info">HORÁRIO:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_horario'] ?></td>
            </tr>
            <tr>
                <td class="info">MATRÍCULA:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_matricula'] ?></td>
                <td></td>
                <td class="info">LOCAL:</td>
                <td class="dado"><?php echo $this->ponto['local'] ?></td>
            </tr>
            <tr>
                <td class="info">ADMISSÃO:</td>
                <td class="dado"><?php echo Data::converterParaBR($this->funcionario['rh_funcionario_data_admissao']) ?></td>
                <td></td>
                <td class="info">COORDENADOR:</td>
                <td class="dado"><?php echo $this->ponto['coordenador'] ?></td>
            </tr>
            <tr>
                <td class="info">CTPS:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_ctps'] ?></td>
            </tr>
            <tr>
                <td class="info">PIS:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_pis_pasep'] ?></td>
            </tr>
        </table>

        <table width="100%" border="0">
            <thead>
                <tr class="tr-border-bottom">
                    <th>Data</th>
                    <th>Dia</th>
                    <th>1º ENT.</th>
                    <th>1º SAI.</th>
                    <th>2º ENT.</th>
                    <th>2º SAI.</th>
                    <th>3º ENT.</th>
                    <th>3º SAI.</th>
                    <th>HI</th>
                    <th>CHP</th>
                    <th>HT</th>
                    <th>HTN</th>
                    <th>HNT</th>
                    <th>DSR</th>
                    <th>Extra</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->registros as $i => $registro) : ?>
                    <tr bgcolor="<?php echo $i % 2 == 0 ? '#FFFFFF' : '#EBF5FF' ?>">
                        <td><?php echo Data::converterParaBR($registro['rh_registro_data']) ?></td>
                        <td><?php echo $registro['rh_registro_dia_semana'] ?></td>
                        <td><?php echo Data::eliminarSegundos($registro['rh_registro_entrada_1']) ?></td>
                        <td><?php echo Data::eliminarSegundos($registro['rh_registro_saida_1']) ?></td>
                        <td><?php echo Data::eliminarSegundos($registro['rh_registro_entrada_2']) ?></td>
                        <td><?php echo Data::eliminarSegundos($registro['rh_registro_saida_2']) ?></td>
                        <td><?php echo Data::eliminarSegundos($registro['rh_registro_entrada_3']) ?></td>
                        <td><?php echo Data::eliminarSegundos($registro['rh_registro_saida_3']) ?></td>
                        <td>&nbsp;</td>
                        <td><?php echo Data::testeFDS($registro['rh_registro_data']) ? '00:00' : '08:00' ?></td>
                        <td><?php echo Data::eliminarSegundos($registro['rh_registro_horas_trabalhadas']) ?></td>
                        <td><?php echo Data::eliminarSegundos($registro['rh_registro_horas_noturno']) ?></td>
                        <td><?php echo Data::eliminarSegundos($registro['rh_registro_horas_desconto']) ?></td>
                        <td><?php echo $registro['rh_registro_dsr'] ?></td>
                        <td><?php echo Data::eliminarSegundos($registro['rh_registro_horas_extra']) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>

            <?php if (strlen($this->mv) > 0): ?>
                <tfoot>
                    <tr class="tr-border-top">
                        <th align="left">TOTAIS</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th><?php echo Data::eliminarSegundos($this->ponto['rh_ponto_total']) ?></th>
                        <th><?php echo Data::eliminarSegundos($this->ponto['rh_ponto_horas_noturno']) ?></th>
                        <th><?php echo Data::eliminarSegundos($this->ponto['rh_ponto_horas_desconto']) ?></th>
                        <th>&nbsp;</th>
                        <th><?php echo Data::eliminarSegundos($this->ponto['rh_ponto_horas']) ?></th>
                    </tr>
                </tfoot>
            <?php endif ?>

        </table>

        <table width="100%" style="margin-top: 100px;">
            <tr>
                <td width="300" style="border-top: 1px solid #000;"><?php echo $this->funcionario['rh_funcionario_nome'] ?></td>
                <td width="100"></td>
                <td align="left">
                    <p>* Registro Justificado/CHP - Carga Horária Prevista</p>
                    <p>HT - Horas Trabalhadas/HNT - Horas não trabalhadas</p>
                    <p>HI - Horário Itinerário/HTN - Horas Trabalhadas Noturnas</p>
                </td>
            </tr>
        </table>

        <?php
        $pagina1 = ob_get_clean();
        ob_start();
        ?>

        <table width="100%">
            <tr>
                <td align="left"><img src="/img/logoH.png" width="100"/></td>
                <td><h1>Espelho de Ponto</h1></td>
                <td width="200">2/2</td>
            </tr>
        </table>

        <table width="100%" style="margin: 30px 0;">
            <tr>
                <td class="info" width="1">EMPREGADO:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_nome'] ?></td>
                <td></td>
                <td class="info">PERÍODO:</td>
                <td class="dado"><?php echo Data::converterParaBR($this->ponto['rh_ponto_periodo_1']) . ' a ' . Data::converterParaBR($this->ponto['rh_ponto_periodo_2']) ?></td>
            </tr>
            <tr>
                <td class="info">FUNÇÃO:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_funcao'] ?></td>
                <td></td>
                <td class="info">HORÁRIO:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_horario'] ?></td>
            </tr>
            <tr>
                <td class="info">MATRÍCULA:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_matricula'] ?></td>
                <td></td>
                <td class="info">LOCAL:</td>
                <td class="dado"><?php echo $this->ponto['local'] ?></td>
            </tr>
            <tr>
                <td class="info">ADMISSÃO:</td>
                <td class="dado"><?php echo Data::converterParaBR($this->funcionario['rh_funcionario_data_admissao']) ?></td>
                <td></td>
                <td class="info">COORDENADOR:</td>
                <td class="dado"><?php echo $this->ponto['coordenador'] ?></td>
            </tr>
            <tr>
                <td class="info">CTPS:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_ctps'] ?></td>
            </tr>
            <tr>
                <td class="info">PIS:</td>
                <td class="dado"><?php echo $this->funcionario['rh_funcionario_pis_pasep'] ?></td>
            </tr>
        </table>

        <table width="100%" border="0">
            <thead>
                <tr class="tr-border-bottom">
                    <th>Data</th>
                    <th>Dia</th>
                    <th style="text-align: left">Justificativa</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->registros as $i => $registro) : ?>
                    <?php if (strlen($registro['rh_registro_observacoes']) == 0) continue; ?>
                    <tr bgcolor="<?php echo $i % 2 == 0 ? '#FFFFFF' : '#EBF5FF' ?>">
                        <td style="width: 12%"><?php echo Data::converterParaBR($registro['rh_registro_data']) ?></td>
                        <td style="width: 7%"><?php echo $registro['rh_registro_dia_semana'] ?></td>                     
                        <td style="font-size: 9px !important;text-align: justify!important"><?php echo $registro['rh_registro_observacoes'] ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>


        <table width="100%" style="margin-top: 100px;">
            <tr>
                <td width="300" style="border-top: 1px solid #000;"><?php echo $this->funcionario['rh_funcionario_nome'] ?></td>
                <td width="100"></td>
                <td align="left">&nbsp;</td>
            </tr>
        </table>
        <?php $pagina2 = ob_get_clean() ?>

    </body>
</html>
<?php
$html = ob_get_clean();
include 'MPDF/mpdf.php';
$mpdf = new mPDF('utf-8', '', 0, '', 10, 10, 10, 10, 9, 9, '');
$mpdf->WriteHTML($pagina1);
$mpdf->AddPage();
$mpdf->WriteHTML($pagina2);
$mpdf->Output();
