<script>
    var filtros = JSON.stringify(obterFiltros());
</script>
<?php if (isset($this->itensPaginados) && $this->itensPaginados instanceof Zend_Paginator): ?>

    <?php $paginator = $this->itensPaginados->getPages() ?>

    <?php if ($paginator->pageCount): ?>
        <ul class="pagination">
            <?php if (isset($paginator->previous)): ?>
                <li><a class="item-inicial" href="javascript:;" onclick="post('<?php echo $this->url() ?>', {page: '<?php echo $paginator->previous ?>', like: '<?php echo $this->like ?>', filters: filtros})">«</a></li>
            <?php else: ?>
                <li><a class="disabled" href="javascript:void(0);">«</a></li>
            <?php endif; ?>

            <?php foreach ($paginator->pagesInRange as $page): ?>
                <?php if ($page != $paginator->current): ?>
                    <li><a href="javascript:;" onclick="post('<?php echo $this->url() ?>', {page: '<?php echo $page ?>', like: '<?php echo $this->like ?>', filters: filtros})"><?php echo $page ?></a></li>
                <?php else: ?>
                    <li class="active"><a href="javascript:void(0);"><?php echo $page ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if (isset($paginator->next)): ?>
                <li><a href="javascript:;" onclick="post('<?php echo $this->url() ?>', {page: '<?php echo $paginator->next ?>', like: '<?php echo $this->like ?>', filters: filtros})">»</a></li>
            <?php else: ?>
                <li><a class="disabled" href="javascript:void(0);">»</a></li>
                <?php endif ?>
        </ul>
    <?php endif; ?>

<?php endif; ?>