<div class="well well-small"><i class="icon-plus-sign"></i>&nbsp;<strong>Relatório de Procedimentos Realizados</strong></div>
<div><?php echo $this->erros ?></div>
<div class="well well-small div-transparente">
    <form action="/documento-operacional/relatorio-procedimentos-realiz" method="post">
        <div class="row-fluid">
            <div class="span3">
                <label>Exame</label>
                <div class="row-fluid">
                    <select name="produtos" class="span">
                        <option value="0">---</option>
                        <?php foreach ($this->produtos as $key => $value) : ?>
                            <option value="<?php echo $value['produto_id'] ?>" ><?php echo $value['produto_nome'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="span3">
                <label>Período</label>
                <div class="row-fluid">
                    <div class="span5">
                        <input type="text" class="span mask-data calendario" name="data1" value="<?php echo date('01/01/2014') ?>"/>
                    </div>
                    <div class="span2">
                        <input type="text" class="span" value="à" disabled="disabled" style="text-align: center;"/>
                    </div>
                    <div class="span5">
                        <input type="text" class="span mask-data calendario" name="data2" value="<?php echo date('d/m/Y') ?>"/>
                    </div>
                </div>
            </div>

            <div class="span3">
                <label>Tipo de Exame</label>
                <div class="row-fluid">
                    <select name="tipoexame_id" class="span">
                        <option value="0">---</option>
                        <?php foreach ($this->colecaoTiposExames as $key => $value) : ?>
                            <option value="<?php echo $value['tipoexame_id'] ?>" ><?php echo $value['tipoexame_nome'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="span3">
                <label>N°.Contrato</label>
                <div class="row-fluid">
                    <input type="text" class="span" name="contrato_numero" value=""/>
                </div>
            </div>
        </div>


        <div class="row-fluid">
            
            <div class="span3">
                <label>CNPJ</label>
                <input type="text" class="span mask-cnpj" name="empresa_cnpj" value=""/>
            </div>
            
            <div class="span3">
                <label>Razão Social</label>
                <input type="text" class="span" name="empresa_razao" value=""/>
            </div>
            
            <div class="span1">
                <label>&nbsp;</label>
                <button class="span btn btn-success" type="submit">Enviar</button>
            </div>
        </div>


    </form>
</div>
<script>
    $("#empresa").change(function () {
        if (parseInt(this.value) > 0) {
            $("#unidades").css('display', 'none');
            $("#contratos").css('display', 'block');
            $.post('/ajax/json/servico/obter-contratos-pela-empresa', {empresa: this.value}, function (r) {
                adicionarOptions("contrato", r, "contrato_id", "contrato_numero", true);
            }, 'json');
        } else {
            $("#unidades").css('display', 'block');
            $("#contratos").css('display', 'none');
        }
    });
</script>