<div class="row-fluid">
    <div class="well well-small">
        <form action="/documento-operacional/imprimir-fatura" method="post" >
            <div class="">
                <p>Vamos Faturar?</p>
            </div>
            <div class="row-fluid">
                <div class="span6">
                    <label>&nbsp;</label>
                    <button class="btn btn-success" type="submit"><i class="icon-print"></i>&nbsp;Clique Aqui</button>
                </div>
            </div>
        </form>
    </div>
</div>
