<?php
if (isset($_GET['layout'])) {
    include 'layout-new.phtml';
    exit;
}

#echo '<pre>';var_export($_SESSION);echo '</pre>';
$subdominiosDesenvolvimento = array(
    'desenvportal.hiestgroup.com.br'
);
$larguraFrame = '0';
$alturaFrame = '0';
$bordaFrame = '0';
$estilo = 'margin: 0px;padding: 0px;visibility: hidden';
$meuSubdominio = $_SERVER['HTTP_HOST'];
if (in_array($meuSubdominio, $subdominiosDesenvolvimento)) {
    $larguraFrame = '770';
    $alturaFrame = '350';
    $bordaFrame = '1';
    $estilo = '';
}
?>
<?php
$dataexplodida = array();

switch (date('m')) {
    case 1: $dataexplodida[1] = "janeiro";
        break;
    case 2: $dataexplodida[1] = "fevereiro";
        break;
    case 3: $dataexplodida[1] = "março";
        break;
    case 4: $dataexplodida[1] = "abril";
        break;
    case 5: $dataexplodida[1] = "maio";
        break;
    case 6: $dataexplodida[1] = "junho";
        break;
    case 7: $dataexplodida[1] = "julho";
        break;
    case 8: $dataexplodida[1] = "agosto";
        break;
    case 9: $dataexplodida[1] = "setembro";
        break;
    case 10: $dataexplodida[1] = "outubro";
        break;
    case 11: $dataexplodida[1] = "novembro";
        break;
    case 12: $dataexplodida[1] = "dezembro";
        break;
}
switch (date('D')) {
    case 'Mon': $dataexplodida[0] = "Segunda-Feira";
        break;
    case'Tue': $dataexplodida[0] = "terça-feira";
        break;
    case'Wed': $dataexplodida[0] = "Quarta-feira";
        break;
    case 'Thu': $dataexplodida[0] = "Quinta-Feira";
        break;
    case 'Fri': $dataexplodida[0] = "Sexta-Feira";
        break;
    case 'Sat': $dataexplodida[0] = "Sabado";
        break;
    case 'Sun': $dataexplodida[0] = "Domingo";
        break;
}
?>
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8"/>
        <title>Portal do Cliente</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="stylesheet" href="/bootstrap/css/bootstrap.css" type="text/css" media="all"/>
        <link rel="stylesheet" href="/bootstrap/css/bootstrap-responsive.css" type="text/css" media="all"/>
        <link rel="stylesheet" href="/css/geral.css" type="text/css" media="all"/>
        <script src="/js/jquery-1.10.2.min.js" type="text/javascript"></script>
        <script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
        <script src="/js/geral.js" type="text/javascript"></script>
        <script src="/js/util.js" type="text/javascript"></script>
        <script src="/plugins/ckeditor/full/ckeditor.js" type="text/javascript"></script>
        <script src="/bootstrap/js/bootstrap.js" type="text/javascript"></script>
        <!--
               Incluindo os arquivos do plug-ins do boostrap
               Plug-in: bootstrap-datetimepicker
               Documentação em: http://tarruda.github.io/bootstrap-datetimepicker/
        -->
        <link rel="stylesheet" href="/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" type="text/css" media="screen" charset="utf-8" />
        <script type="text/javascript" src="/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
        <!-- Fim da inclusão de arquivos do plug-in -->
        <!-- css menu maker -->
        <link href="/cssmenumaker/styles.css" rel="stylesheet" type="text/css">
        <noscript><meta http-equiv="Refresh" content="0;url=/auth/" /></noscript>
    </head>
    <body style="background-color: #fff; border: 0px solid ">
        <div id="sombra"></div>
        <div id="aguarde" style="margin-top: 45px;"></div>
        <?php #var_dump($_SESSION['empresa']['empresa_razao']); ?>

        <div id="portal-hiest-area-menu" style="padding: 0px">
            <?php echo $this->render('menu2.phtml'); ?>
        </div>

        <?php if (isset($this->mapeamentoAcesso) && is_array($this->mapeamentoAcesso)): ?>
            <?php
            $modulo = $this->mapeamentoAcesso['modulo'];
            $controlador = $this->mapeamentoAcesso['controlador'];
            $acao = str_ireplace('index', 'início', $this->mapeamentoAcesso['acao']);
            $navegacao = array($modulo . '&nbsp;', $controlador . '&nbsp;', $acao);
            ?>
            <?php if ($this->mapeamentoAcesso['controlador'] != "index"): ?>
                <div id="detalhe-navegacao" style="width: 98.7%; height: 13px" class="row-fluid"><p><i class="icon-map-marker"></i>&nbsp;Você está em:&nbsp;<?php echo implode('<i class=" icon-chevron-right"></i>&nbsp;', $navegacao) ?></p></div>
            <?php endif; ?>
        <?php endif ?>


        <div class="container-fluid" id="portal-hiest-area-corpo-pagina">

            <div class="row-fluid">
                <div class="span12">
                    <div id="alertas"></div>
                    <?php if (isset($this->erro)) : ?>
                        <div class="alert alert-danger">
                            <?php echo $this->erro; ?>
                        </div>
                    <?php else : ?>
                        <?php echo $this->layout()->content; ?>
                    <?php endif; ?>
                </div>
            </div>

        </div>

        <footer style="background-image: url('/cssmenumaker/images/nav-bg.png'); background-repeat: repeat-x; background-color: rgb(31,31,31);padding: 10px;color: #fcfcfc; padding-top: 5px; padding-bottom: 25px;bottom: 0px;margin-bottom: 0px;">
            <div style="border-bottom: 1px solid; padding: 0px; margin: 0px; font-size: 11px">
                &copy; Hiest Assessoria Ltda. 2014. Todos os direitos reservados
            </div>
        </footer>

        <iframe style="<?php echo $estilo ?>" id="iframe-receptor" name="iframe-receptor" width="<?php echo $larguraFrame ?>" height="<?php echo $alturaFrame ?>" frameborder="<?php echo $bordaFrame ?>"></iframe>

        <script>
            ucase();
        </script>

        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-66852788-1', 'auto');
            ga('send', 'pageview');

        </script>

    </body>
</html>