<img style="border: none;" src="/img/imagem-lateral-portal.png"   usemap="#mapeamentoMenu"/>

<map name="mapeamentoMenu">
    <area shape="rect" coords="0,0,124,142" href="/contrato/" alt="Meu contrato" title="Meu contrato"/>
    <area shape="rect" coords="248,0,128,142" href="/agenda/" alt="Minha agenda de exames" title="Minha agenda de exames" />
    <area shape="rect" coords="0,292,128,142" href="/funcionario/" alt="Meus funcionários" title="Meus funcionários" />
    <area shape="rect" coords="248,292,128,142" href="/fatura/" alt="Minhas faturas" title="Minhas faturas" />
    <area shape="rect" coords="0,484,128,142" href="/documento/" alt="Meus documentos" title="Meus documentos" />
    <area shape="rect" coords="248,484,128,142" href="/relatorio/" alt="Meus relatórios" title="Meus relatórios" />
</map>