<!-- Codigo preparado para receber o menu preto
<?php $menus = array(); ?>
<ul class="nav">
    <li><a class="" href="/index/"><i class="icon-briefcase icon-white"></i>&nbsp;Meu Contrato </a></li>
    <li><a class="" href="/agenda/"><i class="icon-calendar icon-white"></i>&nbsp;Minha Agenda</a></li>
    <li><a class="" href="/funcionario"><i class="icon-user icon-white"></i>&nbsp;Meus Funcionários</a></li>
    <li><a class="" href="/fatura"><i class="icon-file icon-white"></i>&nbsp;Minhas Faturas</a></li>
    <li><a class="" href="/documento/"><i class="icon-folder-close icon-white"></i>&nbsp;Meus Documentos</a></li>
    <li><a class="" href="/relatorio/"><i class=" icon-th-large icon-white"></i>&nbsp;Meus Relatórios</a></li>
<?php foreach ($menus as $mod => $servicos): ?>
            <li class="dropdown">
                <a id="drop<?php echo $mod; ?>" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><?php echo $mod; ?><b class="caret"></b></a>
    <?php if (count($servicos) > 0): ?>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="drop<?php echo $mod; ?>">
        <?php foreach ($servicos as $serv): ?>
                                    <li><a tabindex="-1" href="<?php echo $serv['url']; ?>"><?php echo $serv['nome']; ?></a></li>
        <?php endforeach ?>
                        </ul>
    <?php endif ?>
            </li>
<?php endforeach ?>
</ul>
-->
<?php $menus = array(); ?>
<ul class="nav">
    <li><a class="" href="/index/"><i class="icon-briefcase"></i>&nbsp;HOME </a></li>
    <li><a class="" href="/contrato/"><i class="icon-briefcase"></i>&nbsp;Meu Contrato </a></li>
    <li><a class="" href="/agenda/"><i class="icon-calendar"></i>&nbsp;Minha Agenda</a></li>
    <li><a class="" href="/funcionario"><i class="icon-user"></i>&nbsp;Meus Funcionários</a></li>
    <li><a class="" href="/fatura"><i class="icon-file"></i>&nbsp;Minhas Faturas</a></li>
    <li><a class="" href="/documento/"><i class="icon-folder-close"></i>&nbsp;Meus Documentos</a></li>
    <li><a class="" href="/relatorio/"><i class=" icon-th-large"></i>&nbsp;Meus Relatórios</a></li>
    <?php foreach ($menus as $mod => $servicos): ?>
        <li class="dropdown">
            <a id="drop<?php echo $mod; ?>" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><?php echo $mod; ?><b class="caret"></b></a>
            <?php if (count($servicos) > 0): ?>
                <ul class="dropdown-menu" role="menu" aria-labelledby="drop<?php echo $mod; ?>">
                    <?php foreach ($servicos as $serv): ?>
                        <li><a tabindex="-1" href="<?php echo $serv['url']; ?>"><?php echo $serv['nome']; ?></a></li>
                    <?php endforeach ?>
                </ul>
            <?php endif ?>
        </li>
    <?php endforeach ?>
</ul>