<table  border="0" cellpadding="1" cellspacing="0" style="font-family: arial; font-size: 22px;">
    <tr>
        <td width="12%"><img src="/img/logo-relatorio.png" /></td>
        <td style="text-align: center">
            <p style="color: dark;">
                <strong>
                    Ficha Médica de Exame Ocupacional
                </strong>
            </p>
            <p><[atributoTipoExame]/></p>
        </td>
    </tr>
</table>

<!--   INFORMAÇÕES DA PÁGINA-->
<table  style="border-collapse: collapse; font: normal 11px Arial;  width: 100%;">
    <tr>
        <td colspan="8" class="etiqueta" style="font-weight: none; border: 1px solid #ddd; border-bottom: none; border-left: none; border-right: none;">{CIDADE}, <?php echo date('d'); ?> de <?php echo Util::nomeDoMes(date('m')); ?> de <?php echo date('Y'); ?></td>
        <td colspan="8" style="text-align: right; font-weight: none; border: 1px solid #ccc; border-bottom: none; border-left: none; border-right: none;">Página {PAGENO} de {nbpg} </td>
    </tr>
    <tr>
        <td colspan="18" class="etiqueta" style="border: 1px solid #ccc; border-bottom: none; border-left: none; border-right: none;">&nbsp;</td>
    </tr>   
</table>
<!--   FIM DE INFORMAÇÕES PÁGINA-->