

<div class="row-fluid">
    <div class="well well-small"><i class="icon-filter"></i><strong>&nbsp;Contratos e Proposta</strong></div>
</div>

<form action="" method="post" target="_blank">
    <div class="row-fluid">

        <div class="span2">
            <label>Data de Início</label>
            <input type="text" class="span mask-data" name="param_data_inicio" />
        </div>

        <div class="span2">
            <label>Data de Término</label>
            <input type="text" class="span mask-data" name="param_data_termino"/>
        </div>

        <div class="span3">
            <label>&nbsp;</label>
            <button style="" type="submit" class="btn"><span class="icon-ok"></span>&nbsp;Processar</button>
        </div>

    </div>

</form>