

<div class="row-fluid">
    <div class="well well-small"><i class="icon-filter"></i><strong>&nbsp;Treinamentos Realizados</strong></div>
</div>

<form action="" method="post" target="_blank">
    <div class="row-fluid">

        <div class="span2">
            <label>Data de Início</label>
            <input type="text" class="span mask-data" name="treinamento_agenda_data_inicio" />
        </div>

        <div class="span2">
            <label>Data de Início</label>
            <input type="text" class="span mask-data" name="treinamento_agenda_data_termino"/>
        </div>


        <div class="span4">
            <label>Treinamento</label>
            <select name="treinamento_agenda_fk_produto_id" class="span">
                <option value="0">--</option>
                <?php foreach ($this->colecaoProdutos as $item): ?>
                    <option value="<?php echo $item['produto_id'] ?>"><?php echo $item['produto_nome'] ?></option>
                <?php endforeach ?>
            </select>
        </div>


        <div class="span4">
            <label>Instrutor</label>
            <select name="treinamento_agenda_fk_usuario_id_instrutor" class="span">
                <option value="0">--</option>
                <?php foreach ($this->colecaoUsuarioInstrutores as $usuario): ?>
                    <option value="<?php echo $usuario['usuario_id'] ?>"><?php echo $usuario['pessoa_nome'] ?></option>
                <?php endforeach ?>
            </select>
        </div>


    </div>


    <div class="row-fluid">
        <div class="span6">
            <label>Empresa</label>
            <select name="treinamento_agenda_fk_empresa_id" class="span">
                <option value="0">--</option>
                <?php foreach ($this->colecaoEmpresas as $item): ?>
                    <option value="<?php echo $item['empresa_id'] ?>"><?php echo $item['empresa_fantasia'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
        <div class="span6">
            <label>Formato de Saída</label>
            <select name="param_formato_saida" class="span">
                <option value="xls">XLS</option>
                <option value="pdf">PDF</option>
            </select>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span2">
            <button type="submit" class="btn"><span class="icon-ok"></span>&nbsp;Processar</button>
        </div>
    </div>

</form>