<?php echo $this->erro2 ? ('<div class="alert alert-danger">' . $this->erro2 . '</div>') : ''; ?>

<div class="row-fluid">

    <div>

        <div class="well well-small"><i class="icon-check"></i>&nbsp;<strong>Emitir Lista de Evidência</strong></div>

        <form action="" method="post" target="_blank">

            <div class="row-fluid">

                <div class="span2">
                    <label>Data Início *</label>
                    <input class="span mask-data" type="text" name="data_inicio" value="01/<?php echo date('m/Y') ?>" />
                </div>

                <div class="span2">
                    <label>Data Fim *</label>
                    <input class="span mask-data" type="text" name="data_fim" value="31/<?php echo date('m/Y') ?>" />
                </div>

                <div class="span3">
                    <label>Médico</label>
                    <select class="span" id="medicos" name="especialista_id">
                        <option value="0">-- Não Obrigatório --</option>
                        <?php foreach ($this->medicos as $medico) : ?>
                            <option value="<?php echo $medico['pessoa_especialidade_id'] ?>"><?php echo $medico['pessoa_nome'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <div class="span3">
                    <label>Exame *</label>
                    <select class="span" id="exames" name="exame_id">
                        <?php foreach ($this->exames as $exame) : ?>
                            <option value="<?php echo $exame['produto_id'] ?>"><?php echo $exame['produto_nome'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <div class="span2">
                    <label>&nbsp;</label>
                    <button class="span btn btn-success" type="submit"><i class="icon-print"></i>&nbsp;Imprimir</button>
                </div>

            </div>

        </form>

    </div>

</div>

<script>
    $('#medicos').change(function() {
        carregarExamesPeloEspecialista(this.value)
    });
    carregarExamesPeloEspecialista = function(pessoaespecialidadeid) {
        $.post('/ajax/json/servico/obter-exames-pelo-especialista', {id: pessoaespecialidadeid}, function(examesjson) {
            if (typeof examesjson === 'object') {
                var onde = document.getElementById('exames');
                onde.innerHTML = '';
                for (var i = 0; i < examesjson.length; i++) {
                    var novo = document.createElement('option');
                    novo.value = examesjson[i].produto_id;
                    novo.text = examesjson[i].produto_nome;
                    onde.appendChild(novo);
                }
            } else {
                Util.alerta('danger', examesjson);
            }
        }, 'json');
    }
</script>