<?php echo isset($this->erros) && !empty($this->erros) ? ('<div class="alert alert-danger">' . implode('<br/>', $this->erros) . '</div>') : '' ?>

<div class="well well-small"><i class="icon-tasks"></i>&nbsp;<strong>RELAÇÃO DE AGENDADOS</strong></div>

<form action="" method="post" target="_blank">

    <div class="well well-small div-transparente">

        <div class="row-fluid">

            <div class="span2">
                <label>Período</label>
                <div class="row-fluid">
                    <div class="span5">
                        <input type="text" class="span mask-data" name="data1" value=""/>
                    </div>
                    <div class="span2">
                        <input type="text" class="span" value="à" disabled="disabled" style="text-align: center;"/>
                    </div>
                    <div class="span5">
                        <input type="text" class="span mask-data" name="data2" value=""/>
                    </div>
                </div>
            </div>

            <div class="span1">
                <label>Fase</label>
                <select class="span" name="fase">
                    <option value="0">TODAS</option>
                    <option value="1">1º FASE</option>
                    <option value="2">2º FASE</option>
                </select>
            </div>

            <div class="span1">
                <label>Tipo</label>
                <select class="span" name="tipo">
                    <option value="0">TODOS</option>
                    <?php foreach (Util::consultaDireta("SELECT * FROM tipoexame WHERE tipoexame_status = 0 ORDER BY tipoexame_nome ASC") as $item): ?>
                        <option value="<?php echo $item['tipoexame_id'] ?>"><?php echo $item['tipoexame_nome'] ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <?php $unidade = $_SESSION['usuario']['unidadeativa']['unidade_id']; ?>
            <div class="span2">
                <label>Empresa</label>
                <select class="span" name="empresa">
                    <option value="0">TODAS</option>
                    <?php foreach (Util::consultaDireta("SELECT * FROM empresa WHERE empresa.empresa_status = 0 and empresa.empresa_tipo = 'CLIENTE' AND empresa.fk_unidade_id = {$unidade} ORDER BY empresa.empresa_fantasia ASC") as $item): ?>
                        <option value="<?php echo $item['empresa_id'] ?>"><?php echo $item["empresa_fantasia"] . ' (' . Util::preencherComZero($item['empresa_id'], 5) . ')' ?></option>
                    <?php endforeach ?>
                </select>
            </div>

            <div class="span2">
                <label>Especialista</label>
                <select class="span" name="especialista">
                    <option value="0">TODOS</option>
                    <?php foreach (Util::consultaDireta("SELECT * FROM pessoa_especialidade JOIN pessoa ON pessoa.pessoa_id = pessoa_especialidade.fk_pessoa_id JOIN especialidade ON especialidade.especialidade_id = pessoa_especialidade.fk_especialidade_id WHERE pessoa.pessoa_status = 0 AND especialidade.especialidade_status = 0 ORDER BY pessoa_nome ASC") as $item): ?>
                        <option value="<?php echo $item['pessoa_especialidade_id'] ?>"><?php echo $item['pessoa_nome'] ?></option>
                    <?php endforeach ?>
                </select>
            </div>

            <div class="span2">
                <label>Produto</label>
                <select class="span" name="produto">
                    <option value="0">TODOS</option>
                    <?php foreach (Util::consultaDireta("SELECT * FROM produto JOIN categoriadoproduto ON categoriadoproduto.categoriadoproduto_id = produto.fk_categoriadoproduto_id WHERE produto.produto_status = 0 AND categoriadoproduto.categoriadoproduto_status = 0 AND categoriadoproduto.categoriadoproduto_codigo_fixo = '0002' ORDER BY produto_nome ASC") as $item): ?>
                        <option value="<?php echo $item['produto_id'] ?>"><?php echo $item['produto_nome'] ?></option>
                    <?php endforeach ?>
                </select>
            </div>

            <div class="span1">
                <label>Modo</label>
                <select class="span" name="modo">
                    <option value="0">VISUALIZAR</option>
                    <option value="1">PLANILHA</option>
                </select>
            </div>

            <div class="span1">
                <label>&nbsp;</label>
                <input type="submit" class="span btn btn-success" value="Enviar"/>
            </div>

        </div>

    </div>

</form>