<!--<script type="text/javascript">
    $(document).ready(function() {
        $(".item-exame").attr("checked", "checked");
        $("#marcar-todos").hide();

        $("#marcar-todos").click(function() {
            $(".item-exame").prop('checked', true);
            $("#marcar-todos").hide();
            $("#desmarcar-todos").show();
        });
        
        $("#desmarcar-todos").click(function() {
            $(".item-exame").prop('checked', false);
            $("#marcar-todos").show();
            $("#desmarcar-todos").hide();
        });
    });
</script>-->


<div class="row-fluid">
    <div class="well well-small">
        <form action="/documento-operacional/relatorio-empresa" method="post" >
            <div class="">
                <p><i class="icon-plus-sign"></i>&nbsp;<strong>Relatório de Empresas</strong></p>
            </div>

            <!--            <div class="row-fluid">
                            <div class="span2">
                                <label>Data Início</label>
                                <input value="<?php #echo date('d/m/Y');  ?>" name="data_inicio" type="text" class="span mask-data" />
                            </div>
            
                            <div class="span2">
                                <label>Data Fim</label>
                                <input value="<?php #echo date('d/m/Y');  ?>" name="data_fim" type="text" class="span mask-data" />
                            </div>
                        </div>
            
                        <p><i class="icon-check"></i>&nbsp;<strong>Exames</strong></p>
                        <p id="area-marcar-todos">
                            <a href="javascript:;" class="marcador btn btn-small btn-inverse" id="marcar-todos"><i class=" icon-ok icon-white"></i>&nbsp;Marcar Todos</a>
                            <a href="javascript:;" class="marcador btn btn-small btn-danger" id="desmarcar-todos"><i class="icon-remove-circle icon-white"></i>&nbsp;Desmarcar Todos</a>
                        </p>
            
                        <div class="row-fluid">
                            <table  style="border: 0px solid #ccc; font: normal 11px Arial; font-weight: bold; width: 100%; ">
                                <tr> 
            <?php #foreach ($this->produtos as $prod) : ?>
            
                                        <td style="width:460px; float:left;" >
                                            <label class="checkbox" >
                                                <input class="item-exame" type="checkbox"  name="produto_id[]" value="<?php #echo $prod['produto_id'];  ?>" />&nbsp;<?php #echo $prod['produto_nome'];  ?>
                                            </label>
                                        </td>
            
            <?php #endforeach; ?>
                                </tr>
                            </table>
                        </div>-->

            <div class="row-fluid">
                <div class="span6">
                    <label>&nbsp;</label>
                    <button class="btn btn-success" type="submit"><i class="icon-print"></i>&nbsp;Imprimir</button>
                </div>
            </div>
        </form>
    </div>

</div>
